{% set name = "ncpol2sdpa" %}
{% set version = "1.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71d250cf8cf5fd9f8f6efe3a3e0d79b535f8c36794977c4ee561e49a810604de

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - sympy

test:
  requires:
    - python {{ python_min }}
  imports:
    - ncpol2sdpa

about:
  home: http://github.com/peterwittek/ncpol2sdpa
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Solve global polynomial optimization problems of either commutative variables or noncommutative operators through a semidefinite programming (SDP) relaxation'
  doc_url: https://ncpol2sdpa.readthedocs.org/
  dev_url: https://github.com/peterwittek/ncpol2sdpa

extra:
  recipe-maintainers:
    - peterwittek
