# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "X39deJShzTdCJiR/xroXGHvTfu/wP0/BrCS3kLhl6M4OKN9TfmPGjeNAqHqGhBYXnH9VWVVV0w5robwBsa6rMiJ+dJMw9EvVOMwpHWEmNi8lSKLRdDv1ToM/u5ijP8ZebY03JBZw78wmNuoIvyvsqq6rPMCa1DhiVzjtxws+SFrSsdYQtqdrGr7uLa3a4uROPHl06IRjJgy1twb7DIawRxkbQ6jibRyHT9WbiCLaT0aSH5EklATg/yU/XwQqCD6CPHnDXzNK7RPMX0m9N1WvGgd79q+1hrml3siQfy+H4gfy/Sf/c1O7841FpCEiPbx/ndganGgTkmMaRwN1pQ6hL53tNrUtEqk7VhcFX2Ipdv26gML3lOoCrPaSebAw7q/tRVyP/0+1OQs2ipDOdnTIU0h6zvUel/AzhrRXAHTfrQom7oXC6XjtxbuFgy6zADQVFr7Dx+/Z+7pWJwpOvPwGWAmHLgp8RfA8k4VMitNGcbb7+tEpSZr67VvUKLVoPUjTGGMSyYDwe8/GbaKgG54oPa2FBcFe93jD75bGRvZB4FIAEX90DuiRx4OwfvGgnwZOQmk1Ct1hgAdtocy0gjzTcCq014Nxrae37eWzAujk26uDKeWMpiWN4vHqCE/z92pe1WcLij5i5nqa09GAM1FO9VfzKffbaGy+VGsGNnMoxt8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
