travis:
  secure:
    BINSTAR_TOKEN: nJ0IOMhuTZkBu95khOMXysvKHz2XS7EngjCyFiWUvNeJZw71p/MbUKfDasfZkzBHt4eqjX7v1dcXbwsA8m/LcCcabXGKcj4XOfiheHTgihtSZkOC+yGN1s4doHAyWBN7yqxtz0lBX6Dg8aI8OaxXT6qNnH384CpJNNfSg1X/lJeOZ2xj7FCpSnyQ7CknFW0FGgGBM3ipKnHgzaSmNKJS2FGwxj+xzkJRiaQdFEmlySvL1NLI3n1b9oVKaMHmD0GrY12acEA3h9xSQnwfTVkipp9LdeK7JxUtWtzcfmUWrM83Yu5OnPFSH9xHU5k5UmH0qnd+w8YA5nhH22I6nG9wZaPM42+Qd3KobAejHZOHytPjW/BafsRIUYsjjaDGluUxGOQrlTDDfMRMFnivlYmqWvI+eDMussGie0umrCOb9QZorRRDZ/QeXMeVMPCW+h/Aa2laXDmCg61jHlGkCQ0gnFINHn+w0yCiXpAmhRV7pxDhpC3HMG8TaLj0gu08HoAYNble78aIkr5JFlfu0vuUgF9hvh5kKJgewI1nIFslF/EBlho9R0u0T87xfsqiRj83oKEnJRiIvC1wd2f+zbtS7YyB+Bf4e9eH+ZjIete/lyAUZc+1KOnYFXrGnjxXl/JhBSsQy7QdqTkHdNys+0iohSnTbzpKewSzMnkekmAgsCQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
