travis:
  secure:
    BINSTAR_TOKEN: X39deJShzTdCJiR/xroXGHvTfu/wP0/BrCS3kLhl6M4OKN9TfmPGjeNAqHqGhBYXnH9VWVVV0w5robwBsa6rMiJ+dJMw9EvVOMwpHWEmNi8lSKLRdDv1ToM/u5ijP8ZebY03JBZw78wmNuoIvyvsqq6rPMCa1DhiVzjtxws+SFrSsdYQtqdrGr7uLa3a4uROPHl06IRjJgy1twb7DIawRxkbQ6jibRyHT9WbiCLaT0aSH5EklATg/yU/XwQqCD6CPHnDXzNK7RPMX0m9N1WvGgd79q+1hrml3siQfy+H4gfy/Sf/c1O7841FpCEiPbx/ndganGgTkmMaRwN1pQ6hL53tNrUtEqk7VhcFX2Ipdv26gML3lOoCrPaSebAw7q/tRVyP/0+1OQs2ipDOdnTIU0h6zvUel/AzhrRXAHTfrQom7oXC6XjtxbuFgy6zADQVFr7Dx+/Z+7pWJwpOvPwGWAmHLgp8RfA8k4VMitNGcbb7+tEpSZr67VvUKLVoPUjTGGMSyYDwe8/GbaKgG54oPa2FBcFe93jD75bGRvZB4FIAEX90DuiRx4OwfvGgnwZOQmk1Ct1hgAdtocy0gjzTcCq014Nxrae37eWzAujk26uDKeWMpiWN4vHqCE/z92pe1WcLij5i5nqa09GAM1FO9VfzKffbaGy+VGsGNnMoxt8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
